import type { College } from '@/lib/types';

const buildCollege = (
  college: Partial<College> &
    Pick<
      College,
      'id' | 'name' | 'slug' | 'college_type' | 'address' | 'district' | 'management_type' | 'working_hours'
    >
): College => ({
  id: college.id,
  name: college.name,
  slug: college.slug,
  college_type: college.college_type,
  description: college.description ?? null,
  established_year: college.established_year ?? 2010,
  affiliation: college.affiliation ?? 'Manonmaniam Sundaranar University',
  accreditation: college.accreditation ?? 'UGC Recognized',
  recognition: college.recognition ?? 'Govt. of Tamil Nadu',
  management_type: college.management_type,
  logo_url: college.logo_url ?? null,
  image_url: college.image_url ?? 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=900&auto=format&fit=crop&q=80',
  address: college.address,
  district: college.district,
  area: college.area ?? null,
  pincode: college.pincode ?? null,
  latitude: college.latitude ?? null,
  longitude: college.longitude ?? null,
  phone: college.phone ?? null,
  whatsapp: college.whatsapp ?? null,
  email: college.email ?? null,
  website: college.website ?? null,
  working_hours: college.working_hours,
  rating: college.rating ?? 4.2,
  review_count: college.review_count ?? 28,
  view_count: college.view_count ?? 320,
  is_featured: college.is_featured ?? false,
  is_active: college.is_active ?? true,
  created_at: college.created_at ?? '2026-09-24T00:00:00.000Z',
  updated_at: college.updated_at ?? '2026-09-24T00:00:00.000Z',
  history: college.history ?? null,
  vision: college.vision ?? 'To empower rural and town youth of Tenkasi with ethical values, advanced technological skills, and holistic higher education.',
  mission: college.mission ?? 'Provide affordable, career-oriented education with dedicated placement training, research aptitude, and community service.',
  motto: college.motto ?? 'Excellence in Education, Service to Humanity',
  campus_size: college.campus_size ?? '25 Acres Lush Green Campus',
  student_count: college.student_count ?? '2,200+ Students',
  alumni_count: college.alumni_count ?? '12,000+ Alumni Worldwide',
  highlights: college.highlights ?? [
    '2026 Admissions Open with Merit Scholarships',
    '85%+ Campus Placement Record with Leading MNCs',
    '30+ College Bus Transit Routes Across Tenkasi District',
    'State-of-the-Art Laboratories & Digital Smart Classrooms',
  ],
  principal_name: college.principal_name ?? null,
});

export const TENKASI_COLLEGES: College[] = [
  buildCollege({
    id: 'sri-paramakalyani-college',
    name: 'Sri Paramakalyani College, Alwarkurichi',
    slug: 'sri-paramakalyani-college',
    college_type: 'Arts & Science',
    description: 'Premier co-educational diamond jubilee institution founded in 1963 by industrialist Sri T. S. Krishna and inaugurated by President Dr. S. Radhakrishnan. Serving Tenkasi district for 63 years with exceptional science research centers.',
    established_year: 1963,
    address: 'Alwarkurichi, Tenkasi District, Tamil Nadu 627412',
    district: 'Tenkasi',
    area: 'Alwarkurichi',
    pincode: '627412',
    latitude: 8.783,
    longitude: 77.404,
    phone: '04634 283226',
    email: 'spkc_alwarkurichi@yahoo.co.in',
    website: 'https://spkcollege.org/',
    management_type: 'Aided',
    affiliation: 'Manonmaniam Sundaranar University',
    accreditation: 'NAAC Re-accredited with A Grade',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.8,
    review_count: 145,
    is_featured: true,
    campus_size: '50 Acres Campus at the Foothills of Western Ghats',
    student_count: '2,800+ Students',
    alumni_count: '35,000+ Alumni Across the Globe',
  }),
  buildCollege({
    id: 'sri-parasakthi-college-for-women',
    name: 'Sri Parasakthi College for Women, Courtallam',
    slug: 'sri-parasakthi-college-for-women',
    college_type: "Women's College",
    description: 'Autonomous premier diamond jubilee institution established in 1964 by visionary leader Thiru S. Chellapandian. A pioneer in rural women empowerment with 62 years of uninterrupted educational service, NAAC A+ accreditation, and outstanding university ranks.',
    established_year: 1964,
    address: 'Sivan Sannathi Street, Courtallam, Tenkasi District, Tamil Nadu 627802',
    district: 'Tenkasi',
    area: 'Courtallam',
    pincode: '627802',
    latitude: 8.929,
    longitude: 77.269,
    phone: '04633 221244',
    email: 'sriparasakthi1964@gmail.com',
    website: 'https://sriparasakthicollege.edu.in/',
    management_type: 'Aided',
    affiliation: 'Manonmaniam Sundaranar University (Autonomous)',
    accreditation: 'NAAC Accredited with A Grade (Autonomous)',
    working_hours: 'Mon - Sat: 9:00 AM - 4:30 PM',
    rating: 4.9,
    review_count: 210,
    is_featured: true,
    campus_size: '30 Acres Scenic Herbal Campus near Courtallam Falls',
    student_count: '3,200+ Women Scholars',
    alumni_count: '40,000+ Empowered Women Alumni',
  }),
  buildCollege({
    id: 'pasumpon-muthuramalingam-thevar-college',
    name: 'Pasumpon Muthuramalingam Thevar College',
    slug: 'pasumpon-muthuramalingam-thevar-college',
    college_type: 'Arts & Science',
    description: 'Golden Jubilee institution established in 1970 providing 56 continuous years of higher educational service to rural youth in Melaneelithanallur, Sankarankovil, and Tenkasi region with renowned sports and academic legacy.',
    established_year: 1970,
    address: 'Melaneelithanallur, Sankarankovil Taluk, Tenkasi District, Tamil Nadu 627953',
    district: 'Tenkasi',
    area: 'Melaneelithanallur',
    pincode: '627953',
    latitude: 9.112,
    longitude: 77.589,
    phone: '04636 284223',
    email: 'pmtcollege@rediffmail.com',
    management_type: 'Aided',
    affiliation: 'Manonmaniam Sundaranar University',
    accreditation: 'NAAC Accredited',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.5,
    review_count: 98,
    is_featured: true,
    campus_size: '42 Acres Campus with Athletic Stadium',
    student_count: '2,400+ Students',
    alumni_count: '25,000+ Alumni',
  }),
  buildCollege({
    id: 'sri-ram-nallamani-yadava-college',
    name: 'Sri Ram Nallamani Yadava College of Arts and Science',
    slug: 'sri-ram-nallamani-yadava-college',
    college_type: 'Arts & Science',
    description: 'Prestigious institution established in 1994 in Kodikurichi, Tenkasi. Running successfully for 32 years with multi-disciplinary UG and PG courses, modern software labs, and robust bus transit connectivity.',
    established_year: 1994,
    address: 'Kodikurichi, Tenkasi District, Tamil Nadu 627804',
    district: 'Tenkasi',
    area: 'Kodikurichi',
    pincode: '627804',
    latitude: 8.945,
    longitude: 77.348,
    phone: '04633 222325',
    email: 'srnycollege@gmail.com',
    website: 'https://srnycollege.edu.in/',
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.3,
    review_count: 76,
    is_featured: true,
  }),
  buildCollege({
    id: 'csi-jeyaraj-annapackiam-college',
    name: 'CSI Jeyaraj Annapackiam College',
    slug: 'csi-jeyaraj-annapackiam-college',
    college_type: 'Arts & Science',
    description: 'Silver Jubilee co-educational institution established in 1997 at Nallur, Alangulam. Running for 29 years under CSI Tirunelveli Diocese with high moral values, disciplined campus, and skill-based curricula.',
    established_year: 1997,
    address: 'Nallur, Alangulam, Tenkasi District, Tamil Nadu 627853',
    district: 'Tenkasi',
    area: 'Alangulam',
    pincode: '627853',
    latitude: 8.874,
    longitude: 77.502,
    phone: '04633 270275',
    email: 'csijacollege@yahoo.co.in',
    website: 'https://csijacollege.ac.in/',
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.4,
    review_count: 65,
    is_featured: true,
  }),
  buildCollege({
    id: 'mano-college',
    name: 'Manonmaniam Sundaranar University College, Puliangudi',
    slug: 'mano-college',
    college_type: 'Arts & Science',
    description: 'Constituent government college established in 2000 by Manonmaniam Sundaranar University. Running successfully for 26 years providing affordable university education to students from Puliangudi, Sivagiri, Sankarankovil and Kadayanallur taluks.',
    established_year: 2000,
    address: 'Hindu Nadar Uravinmurai Committee Higher Secondary School Campus, T. N. Puthukudi, Puliangudi, Tenkasi, Tamil Nadu 627855',
    district: 'Tenkasi',
    area: 'Puliyangudi',
    pincode: '627855',
    latitude: 8.965,
    longitude: 77.392,
    phone: '04636 356341',
    email: 'msucollege_puliangudi@yahoo.com',
    website: 'https://www.msuniv.ac.in/',
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.2,
    review_count: 52,
    is_featured: true,
  }),
  buildCollege({
    id: 'sardar-raja-college-of-engineering',
    name: 'Sardar Raja College of Engineering',
    slug: 'sardar-raja-college-of-engineering',
    college_type: 'Engineering',
    description: 'Prominent technical engineering institution established in 2000 in Alangulam, Tenkasi. Celebrating 26 years of technical training, AICTE approval, modern laboratories, and thousands of engineering graduates.',
    established_year: 2000,
    address: 'Raja Nagar, Alangulam, Tenkasi District, Tamil Nadu 627808',
    district: 'Tenkasi',
    area: 'Alangulam',
    pincode: '627808',
    latitude: 8.868,
    longitude: 77.498,
    phone: '04633 272798',
    management_type: 'Private',
    affiliation: 'Anna University',
    accreditation: 'AICTE Approved',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 88,
    is_featured: true,
  }),
  buildCollege({
    id: 's-veerasamy-chettiar-college-of-engineering-and-technology',
    name: 'S. Veerasamy Chettiar College of Engineering and Technology',
    slug: 's-veerasamy-chettiar-college-of-engineering-and-technology',
    college_type: 'Engineering',
    description: 'Premier Silver Jubilee engineering institution established in 2001 in Puliyangudi. Marking 25 years of excellence in 2026, offering top-tier branches in CSE, AI & DS, ECE, Mechanical and Civil with extensive corporate placements.',
    established_year: 2001,
    address: 'S V Nagar, Puliyangudi, Tenkasi District, Tamil Nadu 627855',
    district: 'Tenkasi',
    area: 'Puliyangudi',
    pincode: '627855',
    latitude: 8.968,
    longitude: 77.385,
    phone: '04636 234 742',
    website: 'https://www.svce.ac.in/',
    management_type: 'Private',
    affiliation: 'Anna University',
    accreditation: 'AICTE Approved & NBA Accredited Branches',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.4,
    review_count: 139,
    is_featured: true,
    campus_size: '35 Acres High-Tech Campus',
    student_count: '2,100+ Engineers',
    alumni_count: '15,000+ Engineers Worldwide',
  }),
  buildCollege({
    id: 'annai-meenakshi-college',
    name: 'Annai Meenakshi College',
    slug: 'annai-meenakshi-college',
    college_type: 'Arts & Science',
    description: 'Established in 2005 in Puliyangudi, serving the educational aspirations of rural students for 21 years with undergraduate courses in Commerce, Science, and Arts.',
    established_year: 2005,
    address: '70, Pambu Kovil Santhai Road, Puliyangudi, Tamil Nadu 627855',
    district: 'Tenkasi',
    area: 'Puliyangudi',
    pincode: '627855',
    latitude: 8.962,
    longitude: 77.388,
    phone: '094433 81380',
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.0,
    review_count: 35,
    is_featured: false,
  }),
  buildCollege({
    id: 'jp-college-of-arts-and-science',
    name: 'J. P. College of Arts and Science',
    slug: 'jp-college-of-arts-and-science',
    college_type: 'Arts & Science',
    description: 'Founded in 2007 by Grace Swaminathan Educational Trust in Ayikudy. Running for 19 years with excellent infrastructure, modern auditoriums, air-conditioned computer labs, and strong placement drives.',
    established_year: 2007,
    address: 'College Road, Ayikudy, Tenkasi District, Tamil Nadu 627852',
    district: 'Tenkasi',
    area: 'Ayikudy',
    pincode: '627852',
    latitude: 8.981,
    longitude: 77.324,
    phone: '04633 267320',
    website: 'https://jpcas.edu.in/',
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.3,
    review_count: 92,
    is_featured: true,
  }),
  buildCollege({
    id: 'jp-college-of-engineering',
    name: 'J. P. College of Engineering',
    slug: 'jp-college-of-engineering',
    college_type: 'Engineering',
    description: 'Premier engineering institution established in 2008 in Ayikudy near Tenkasi. Running for 18 years, offering innovative engineering degrees, robotics labs, AI curriculum, and top company placements.',
    established_year: 2008,
    address: 'Ayikudy, Tenkasi District, Tamil Nadu 627852',
    district: 'Tenkasi',
    area: 'Ayikudy',
    pincode: '627852',
    latitude: 8.983,
    longitude: 77.326,
    phone: '04633 267321',
    website: 'https://jpcoe.ac.in/',
    management_type: 'Private',
    affiliation: 'Anna University',
    accreditation: 'AICTE Approved',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.3,
    review_count: 85,
    is_featured: true,
  }),
  buildCollege({
    id: 'kamarajar-government-arts-college-surandai',
    name: 'Kamarajar Government Arts College',
    slug: 'kamarajar-government-arts-college-surandai',
    college_type: 'Arts & Science',
    description: 'Key government college established in 2008 at Surandai. Running for 18 continuous years delivering high-quality, zero-tuition government education for thousands of students across the region.',
    established_year: 2008,
    address: 'Surandai, Tenkasi District, Tamil Nadu 627859',
    district: 'Tenkasi',
    area: 'Surandai',
    pincode: '627859',
    latitude: 8.978,
    longitude: 77.424,
    phone: '04633 261450',
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.5,
    review_count: 78,
    is_featured: true,
  }),
  buildCollege({
    id: 'mahakavi-bharathiyar-college-of-engineering-and-technology',
    name: 'Mahakavi Bharathiyar College of Engineering and Technology',
    slug: 'mahakavi-bharathiyar-college-of-engineering-and-technology',
    college_type: 'Engineering',
    description: 'Technical engineering college established in 2008 in Vasudevanallur, running for 18 years under Anna University with focused labs and technical workshops.',
    established_year: 2008,
    address: 'Vasudevanallur, Tenkasi District, Tamil Nadu 627758',
    district: 'Tenkasi',
    area: 'Vasudevanallur',
    pincode: '627758',
    latitude: 9.043,
    longitude: 77.348,
    phone: '04636 241900',
    management_type: 'Private',
    affiliation: 'Anna University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 48,
    is_featured: false,
  }),
  buildCollege({
    id: 'ar-college-of-engineering-and-technology',
    name: 'A.R. College of Engineering and Technology',
    slug: 'ar-college-of-engineering-and-technology',
    college_type: 'Engineering',
    description: 'Engineering institution established in 2009 in Kadayanallur/Tenkasi. Running for 17 continuous years with Anna University affiliation and modern computer and electronics labs.',
    established_year: 2009,
    address: 'Kadayanallur, Tenkasi District, Tamil Nadu 627751',
    district: 'Tenkasi',
    area: 'Kadayanallur',
    pincode: '627751',
    latitude: 8.995,
    longitude: 77.345,
    phone: '04633 241500',
    management_type: 'Private',
    affiliation: 'Anna University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.0,
    review_count: 36,
    is_featured: false,
  }),
  buildCollege({
    id: 'shanmuga-arts-and-science-college',
    name: 'Shanmuga Arts and Science College',
    slug: 'shanmuga-arts-and-science-college',
    college_type: 'Arts & Science',
    description: 'Established in 2010 at Pogai, Tenkasi. Running successfully for 16 years, offering diverse degree programs in Computer Science, Commerce, and Arts with high student satisfaction.',
    established_year: 2010,
    address: '4FQR+Q33, Pogai, Tamil Nadu 627862',
    district: 'Tenkasi',
    area: 'Pogai',
    pincode: '627862',
    latitude: 9.016,
    longitude: 77.438,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    website: 'https://shanmugacollege.edu.in/',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 24,
    is_featured: false,
  }),
  buildCollege({
    id: 'vyasa-arts-and-science-womens-college',
    name: "Vyasa Arts & Science Women's College",
    slug: 'vyasa-arts-and-science-womens-college',
    college_type: "Women's College",
    description: 'Dedicated women’s higher education college established in 2011 in Vasudevanallur. Running for 15 years providing safe, disciplined, and career-oriented learning for female students.',
    established_year: 2011,
    address: 'Madurai - Tenkasi Road, Subramaniapuram, Vellanaikottai Post, Vasudevanallur, Tamil Nadu 627760',
    district: 'Tenkasi',
    area: 'Vasudevanallur',
    pincode: '627760',
    latitude: 9.052,
    longitude: 77.35,
    phone: '04636 242 415',
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.4,
    review_count: 72,
    is_featured: true,
  }),
  buildCollege({
    id: 'avk-arts-and-science-womens-college',
    name: "A.V.K. Arts & Science Women's College",
    slug: 'avk-arts-and-science-womens-college',
    college_type: "Women's College",
    description: 'Women’s arts and science college established in 2012 in Sankarankovil. Running for 14 continuous years with supportive faculty and university rank holders.',
    established_year: 2012,
    address: 'Vadikottai, Sankarankovil, Tenkasi District, Tamil Nadu 627753',
    district: 'Tenkasi',
    area: 'Sankarankovil',
    pincode: '627753',
    latitude: 9.172,
    longitude: 77.532,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.2,
    review_count: 31,
    is_featured: false,
  }),
  buildCollege({
    id: 'vivekananda-college-of-arts-and-science',
    name: 'Vivekananda College of Arts and Science',
    slug: 'vivekananda-college-of-arts-and-science',
    college_type: 'Arts & Science',
    description: 'Established in 2012 in Vellalankulam, Sankarankovil. Running for 14 years with emphasis on character building, national service, and modern digital commerce skills.',
    established_year: 2012,
    address: 'Vellalankulam, Sankarankovil, Tenkasi District, Tamil Nadu 627857',
    district: 'Tenkasi',
    area: 'Sankarankovil',
    pincode: '627857',
    latitude: 9.155,
    longitude: 77.512,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 29,
    is_featured: false,
  }),
  buildCollege({
    id: 'perarignar-anna-science-college',
    name: 'Perarignar Anna Science College',
    slug: 'perarignar-anna-science-college',
    college_type: 'Arts & Science',
    description: 'Science and humanities institution established in 2013 at Dharugapuram, Sivagiri. Running for 13 years with dedicated science laboratories and academic mentoring.',
    established_year: 2013,
    address: 'Dharugapuram, Sivagiri, Tenkasi District, Tamil Nadu 627755',
    district: 'Tenkasi',
    area: 'Sivagiri',
    pincode: '627755',
    latitude: 9.123,
    longitude: 77.412,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.0,
    review_count: 22,
    is_featured: false,
  }),
  buildCollege({
    id: 'mahatma-gandhi-college-of-arts-and-science',
    name: 'Mahatma Gandhi College of Arts and Science',
    slug: 'mahatma-gandhi-college-of-arts-and-science',
    college_type: 'Arts & Science',
    description: 'Established in 2014 in Solaiseri, Sankarankovil. Running for 12 years with Gandhian moral values, skill certification programs, and job placements.',
    established_year: 2014,
    address: 'Solaiseri, Sankarankovil, Tenkasi District, Tamil Nadu 627753',
    district: 'Tenkasi',
    area: 'Sankarankovil',
    pincode: '627753',
    latitude: 9.162,
    longitude: 77.545,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 26,
    is_featured: false,
  }),
  buildCollege({
    id: 'usp-arts-and-science-womens-college',
    name: "U.S.P. Arts and Science Women's College",
    slug: 'usp-arts-and-science-womens-college',
    college_type: "Women's College",
    description: 'Women’s institution established in 2014 in Kodikurichi, Tenkasi. Running for 12 years with safe campus transport, hostel facilities, and holistic personality development.',
    established_year: 2014,
    address: 'Kodikurichi, Tenkasi District, Tamil Nadu 627804',
    district: 'Tenkasi',
    area: 'Kodikurichi',
    pincode: '627804',
    latitude: 8.948,
    longitude: 77.345,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.2,
    review_count: 34,
    is_featured: false,
  }),
  buildCollege({
    id: 's-thangapazham-agricultural-college',
    name: 'S. Thangapazham Agricultural College',
    slug: 's-thangapazham-agricultural-college',
    college_type: 'Agriculture',
    description: 'Premier agricultural college established in 2015 in Vasudevanallur. Running for 11 continuous years with 100+ acres of agricultural research farm lands, modern polyhouses, and state-wide agribusiness placements.',
    established_year: 2015,
    address: 'Vasudevanallur, Naranapuram, Tamil Nadu 627760',
    district: 'Tenkasi',
    area: 'Vasudevanallur',
    pincode: '627760',
    latitude: 9.049,
    longitude: 77.342,
    phone: '099428 52100',
    management_type: 'Private',
    affiliation: 'Tamil Nadu Agricultural University (TNAU Recognized)',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.6,
    review_count: 98,
    is_featured: true,
    campus_size: '100+ Acres Farm & Research Campus',
    student_count: '1,200+ Agri Scholars',
  }),
  buildCollege({
    id: 'st-joseph-college-of-arts-and-science-vaikalipatti',
    name: 'St. Joseph College of Arts and Science',
    slug: 'st-joseph-college-of-arts-and-science-vaikalipatti',
    college_type: 'Arts & Science',
    description: 'Co-educational college established in 2015 at Vaikalipatti, Mettur. Running for 11 years with modern classrooms and focused academic guidance for rural youth.',
    established_year: 2015,
    address: 'Vaikalipatti, Mettur, Tenkasi District, Tamil Nadu 627808',
    district: 'Tenkasi',
    area: 'Mettur',
    pincode: '627808',
    latitude: 8.892,
    longitude: 77.412,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.1,
    review_count: 27,
    is_featured: false,
  }),
  buildCollege({
    id: 'aladi-aruna-college-of-liberal-arts-and-science',
    name: 'Aladi Aruna College of Liberal Arts & Science',
    slug: 'aladi-aruna-college-of-liberal-arts-and-science',
    college_type: 'Arts & Science',
    description: 'Established in 2016 in Sivalarkulam, celebrating a decade of educational service (10 years) in 2026. Offering state-of-the-art multimedia computer labs and university programs.',
    established_year: 2016,
    address: 'Sivalarkulam, Tenkasi District, Tamil Nadu 627853',
    district: 'Tenkasi',
    area: 'Sivalarkulam',
    pincode: '627853',
    latitude: 8.895,
    longitude: 77.472,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.2,
    review_count: 32,
    is_featured: false,
  }),
  buildCollege({
    id: 'valanar-arts-and-science-college',
    name: 'Valanar Arts and Science College',
    slug: 'valanar-arts-and-science-college',
    college_type: 'Arts & Science',
    description: 'Established in 2016 in Kuruvikulam, celebrating 10 years of academic service in 2026 with programs in Commerce, Computer Science, and English.',
    established_year: 2016,
    address: 'Kuruvikulam, Tenkasi District, Tamil Nadu 627754',
    district: 'Tenkasi',
    area: 'Kuruvikulam',
    pincode: '627754',
    latitude: 9.182,
    longitude: 77.625,
    management_type: 'Private',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.0,
    review_count: 20,
    is_featured: false,
  }),
  buildCollege({
    id: 'government-arts-and-science-college-kadayanallur',
    name: 'Government Arts and Science College, Kadayanallur',
    slug: 'government-arts-and-science-college-kadayanallur',
    college_type: 'Arts & Science',
    description: 'Government co-educational college established in 2017 in Kadayanallur. Running for 9 years providing high quality, fee-free higher education to surrounding communities.',
    established_year: 2017,
    address: 'Kadayanallur, Tenkasi District, Tamil Nadu 627751',
    district: 'Tenkasi',
    area: 'Kadayanallur',
    pincode: '627751',
    latitude: 9.075,
    longitude: 77.342,
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.4,
    review_count: 42,
    is_featured: true,
  }),
  buildCollege({
    id: 'st-marys-institute-of-pharmacy',
    name: "St. Mary's Institute of Pharmacy",
    slug: 'st-marys-institute-of-pharmacy',
    college_type: 'Pharmacy',
    description: 'Specialized healthcare & pharmacy institution established in 2018 in Puliyangudi. Running for 8 years with modern pharmaceutical laboratories, drug formulation units, and hospital internship training.',
    established_year: 2018,
    address: '11, Madurai Main Road, Chinthamani, Puliangudi, Kadayanallur (TK), Tenkasi, Tamil Nadu 627855',
    district: 'Tenkasi',
    area: 'Puliyangudi',
    pincode: '627855',
    latitude: 8.964,
    longitude: 77.389,
    phone: '078452 64333',
    management_type: 'Private',
    affiliation: 'The Tamil Nadu Dr. M.G.R. Medical University',
    accreditation: 'Pharmacy Council of India (PCI Approved)',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.5,
    review_count: 38,
    is_featured: true,
  }),
  buildCollege({
    id: 'government-arts-and-science-college-sankarankovil',
    name: 'Government Arts and Science College, Sankarankovil',
    slug: 'government-arts-and-science-college-sankarankovil',
    college_type: 'Arts & Science',
    description: 'Government co-educational college established in 2020 at Sankarankovil. Running for 6 years with modern government facilities, smart classrooms, and top university faculty.',
    established_year: 2020,
    address: 'Sankarankovil, Tenkasi District, Tamil Nadu 627754',
    district: 'Tenkasi',
    area: 'Sankarankovil',
    pincode: '627754',
    latitude: 9.175,
    longitude: 77.535,
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.3,
    review_count: 36,
    is_featured: true,
  }),
  buildCollege({
    id: 'government-arts-and-science-college-for-women-tenkasi',
    name: 'Government Arts and Science College for Women, Tenkasi',
    slug: 'government-arts-and-science-college-for-women-tenkasi',
    college_type: "Women's College",
    description: 'Flagship government women’s college established in 2022 directly in Tenkasi town. Running for 4 years with high student demand, state government scholarships, and holistic career mentorship.',
    established_year: 2022,
    address: 'Tenkasi Town, Tenkasi, Tamil Nadu 627851',
    district: 'Tenkasi',
    area: 'Tenkasi',
    pincode: '627851',
    latitude: 8.959,
    longitude: 77.316,
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University',
    working_hours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    rating: 4.6,
    review_count: 54,
    is_featured: true,
  }),
  buildCollege({
    id: 'msu-college-naduvakurichi-sankarankovil',
    name: 'Manonmaniam Sundaranar University College, Naduvakkurichi',
    slug: 'msu-college-naduvakurichi-sankarankovil',
    college_type: 'Arts & Science',
    description: 'Constituent college of Manonmaniam Sundaranar University situated on Sankarankovil - Virasigamani Road in Naduvakkurichi. Dedicated to providing quality, affordable higher education to rural youth across Sankarankovil, Veerasigamani, and Tenkasi with strong academic faculty and modern amenities.',
    established_year: 2011,
    image_url: '/colleges/msu-naduvakkurichi.jpg',
    address: 'Sankarankovil - Virasigamani Rd, Near Vallaramapuram Bus Stop, Naduvakurichi, Sankarankovil, Tenkasi District, Tamil Nadu 627862',
    district: 'Tenkasi',
    area: 'Sankarankovil',
    pincode: '627862',
    latitude: 9.135,
    longitude: 77.495,
    phone: '04636 281155',
    email: 'msucollegesankarankovil@gmail.com',
    website: 'https://www.msuniv.ac.in/',
    management_type: 'Government',
    affiliation: 'Manonmaniam Sundaranar University (Constituent College)',
    accreditation: 'UGC Recognized Constituent College',
    working_hours: 'Mon - Sat: 10:00 AM - 5:00 PM',
    rating: 4.6,
    review_count: 21,
    is_featured: true,
    campus_size: 'Spacious Green Campus on Sankarankovil - Virasigamani Road',
    student_count: '1,200+ Students',
    alumni_count: '4,500+ Alumni Across Tamil Nadu',
    history: 'Manonmaniam Sundaranar University College at Naduvakkurichi near Sankarankovil was established as a constituent college under Manonmaniam Sundaranar University, Tirunelveli, to bring university-level higher education directly to rural students of the Tenkasi and Sankarankovil taluks. The college has nurtured thousands of graduates across commerce, science, arts, and business management.',
    vision: 'To provide accessible, high-standard higher education and foster academic excellence, moral integrity, and social responsibility among rural students.',
    mission: 'To impart quality education across sciences, humanities, and commerce, bridging the urban-rural divide with modern learning resources and career empowerment.',
    motto: 'Knowledge, Character, and Service to Society',
    highlights: [
      'Constituent College of Manonmaniam Sundaranar University (MSU)',
      'Highly Affordable Government Fee Structure & State Scholarships',
      'Popular UG Programs: B.Sc. Comp Sci, B.Com, B.B.A, B.Sc. Maths & B.A. English',
      'Located on State Highway 409 with frequent bus transit from Sankarankovil and Veerasigamani',
    ],
  }),
];

export const TENKASI_COLLEGE_LOOKUP = new Map(TENKASI_COLLEGES.map((college) => [college.slug, college]));
TENKASI_COLLEGES.forEach((college) => {
  TENKASI_COLLEGE_LOOKUP.set(college.id, college);
});
