-- Migration: Add Manonmaniam Sundaranar University College, Naduvakurichi (Sankarankovil)
-- Matches Google Maps entry and MSU affiliated constituent college directory

INSERT INTO colleges (
  name,
  slug,
  college_type,
  description,
  established_year,
  affiliation,
  accreditation,
  management_type,
  address,
  district,
  area,
  pincode,
  latitude,
  longitude,
  phone,
  email,
  website,
  working_hours,
  rating,
  review_count,
  is_featured,
  is_active
) VALUES (
  'Manonmaniam Sundaranar University College, Naduvakkurichi',
  'msu-college-naduvakurichi-sankarankovil',
  'Arts & Science',
  'Constituent college of Manonmaniam Sundaranar University situated on Sankarankovil - Virasigamani Road in Naduvakkurichi. Dedicated to providing quality, affordable higher education to rural youth across Sankarankovil, Veerasigamani, and Tenkasi with strong academic faculty and modern amenities.',
  2011,
  'Manonmaniam Sundaranar University (Constituent College)',
  'UGC Recognized Constituent College',
  'Government',
  'Sankarankovil - Virasigamani Rd, Near Vallaramapuram Bus Stop, Naduvakurichi, Sankarankovil, Tenkasi District, Tamil Nadu 627862',
  'Tenkasi',
  'Sankarankovil',
  '627862',
  9.135,
  77.495,
  '04636 281155',
  'msucollegesankarankovil@gmail.com',
  'https://www.msuniv.ac.in/',
  'Mon - Sat: 10:00 AM - 5:00 PM',
  4.6,
  21,
  true,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  college_type = EXCLUDED.college_type,
  description = EXCLUDED.description,
  established_year = EXCLUDED.established_year,
  affiliation = EXCLUDED.affiliation,
  accreditation = EXCLUDED.accreditation,
  management_type = EXCLUDED.management_type,
  address = EXCLUDED.address,
  district = EXCLUDED.district,
  area = EXCLUDED.area,
  pincode = EXCLUDED.pincode,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  website = EXCLUDED.website,
  working_hours = EXCLUDED.working_hours,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active;
